name: Changelog Enforcer

on:
  pull_request:
    branches: [ master ]

jobs:
  changelog:
    runs-on: windows-latest
    steps:
    - name: Checkout files
      uses: actions/checkout@v2
    - name: Verify CHANGELOG.md was updated
      uses: dangoslen/changelog-enforcer@v1.0.0
      with:
        changeLogPath: CHANGELOG.md
    - name: Verify VERSION was updated
      uses: dangoslen/changelog-enforcer@v1.0.0
      with:
        changeLogPath: VERSION
    - name: Verify .csproj was updated
      uses: dangoslen/changelog-enforcer@v1.0.0
      with:
        changeLogPath: PlexDvrWaker.csproj
