name: .NET Core Build

on:
  pull_request:
    branches: [ master ]
    types: [ labeled, unlabeled ]

jobs:
  changelog:
    runs-on: windows-latest
    steps:
    - name: Checkout files
      uses: actions/checkout@v2
    - name: Verify changelog was updated
      uses: dangoslen/changelog-enforcer@v1.0.0
      with:
        changeLogPath: 'CHANGELOG.md'
        skipLabel: 'Skip-Changelog'
